const animals = {
  'cat': [
    'Clouded Leopard, N. nebulosa, East Asia',
    'Sunda Clouded Leopard, N. diardi, Southeast Asia',
    'Leopard, P. pardus, Africa/Asia',
    'Tiger, P. tigris, South/East Asia',
    'Snow Leopard, P. uncia, Central/East Asia',
    'Lion, P. leo, Africa/Middle East/South Asia',
    'Jaguar, P. onca, Central/South America',
    'Marbled Cat, P. marmorata, Southeast Asia',
    'Asian Golden Cat, C. temminckii, South/East Asia',
    'Bay Cat, C. badia, Malaysia',
    'Serval, L. serval, South/Central Africa',
    'Caracal, C.caracal, Africa/Middle East/South Asia',
    'African Golden Cat, C. aurata, West Africa',
    'Pampas Cat, L. colocola, East/Central South America',
    'Andean Moutain Cat, L. jacobitus, Andes Mountains',
    'Ocelot, L. pardalis, Northern South America/Central America',
    'Margay, L. wiedii, Northern South America/Central America',
    'Kodkod, L. guigna, Chile',
    "Geoffroy's Cat, L. geoffroyi, Argentina",
    'Oncilla, L. tigrinus, Northern South America',
    'Southern Tigrina, L. guttulus, Southern Brazil',
    'Bobcat, L. rufus, North America',
    'Canada Lynx, L. canadensis, Canada/Alaska',
    'Eurasian Lynx, L. lynx, Northern Asia/Europe',
    'Iberian Lynx, L. pardinus, Southern Spain',
    'Cheetah, A. jabatus, South/East Africa',
    'Cougar, P. concolor, South America/Western North America',
    'Jaguarundi, H. yagouaroundi, Northern/Central South America/Central America',
    "Pallas's Cat, O. manul, Central Asia/Middle East",
    'Rusty-Spotted Cat, P. rubiginosus, India',
    'Leopard Cat, P. bengalensis, South/East Asia',
    'Fishing Cat, P. viverrinus, South Asia',
    'Flat-Headed Cat, P. planiceps, Borneo/Sumatra/Malaysia',
    'Sunda Leopard Cat, P. javanensis, Southeast Asia',
    'Jungle Cat, F. chaus, India/Middle East',
    'Black-Footed Cat, F. nigripes, South Africa',
    'Sand Cat, F. margarita, North Africa/Middle East',
    'Chinese Mountain Cat, F. bieti, China',
    'African Wildcat, F. lybica, Africa/Middle East',
    'European Wildcat, F. silvestris, Europe/Turkey',
    'Domestic Cat, F. catus, Everywhere'
  ],
  'dog': [
    'Short-Eared Dog, A. microtis, Western Amazon Rainforest',
    'African Golden Wolf, C. anthus, North/Northeast Africa',
    'Black-Backed Jackal, C. mesomelas, Southern/Eastern Africa',
    'Coyote, C. latrans, North America',
    'Ethiopian Wolf, C. simensis, Ethiopian Highlands',
    'Golden Jackal, C. aureus, Southern Asia/Middle East/Eastern Europe',
    'Wolf, C. lupus, Europe/Asia/North America',
    'Side-Striped Jackal, C. adustus, Central Africa',
    'Crab-Eating Fox, C. thous, Eastern/Northern South America',
    'Maned Wolf, C. brachyurus, Central South America',
    'Dhole, C. alpinus, Southeast Asia',
    'Culpeo, L. culpeo, Western South America',
    "Darwin's fox, L. fulvipes, Southern Chile",
    'Hoary Fox, L. vetulus, South-Central Brazil',
    'Pampas, L. gymnocercus, Southern South America',
    'Sechuran Fox, L. sechurae, Sechura Desert',
    'South American Gray Fox, L. griseus, Southern South America',
    'African Wild Dog, L. pictus, Various Regions of Africa',
    'Bush Dog, S. venaticus, Northern South America',
    'Raccoon Dog, N. procyonoides, East Asia and Central/Eastern Europe',
    'Bat-Eared Fox, O. megalotis, Southern/Eastern Africa',
    'Arctic Fox, V. lagopus, Arctic North America/Eurasia',
    'Bengal Fox, V. bengalensis, India',
    "Blanford's Fox, V. cana, Middle East/Central Asia",
    'Cape Fox, V. chama, Southern Africa',
    'Corsac Fox, V. corsac, Central Asia',
    'Fennec Fox, V. zerda, Northern Africa',
    'Kit Fox, V. macrotis, Western North America',
    'Pale Fox, V. pallida, Upper Middle Africa',
    "Ruppell's Fox, V. rueppellii, Northern Africa/Middle East",
    'Red Fox, V. vulpes, North America/Europe/Asia/Australia',
    'Swift Fox, V. velox, Western Grasslands of North America',
    'Tibetan Sand Fox, V. ferrilata, Nepal/Western China Plateaus',
    'Gray Fox, U. cinereoargenteus, North/Central America',
    'Islands Fox, U. littoralis, California Channel Islands'
  ],
  'bear': [
    'Giant Panda, Ailuropoda melanoleuca, China',
    'Spectacled Bear, Tremarctos ornatus, Northwest South America',
    'Sloth Bear, Melursus ursinus, India',
    'Sun Bear, Helarctos malayanus, Southeast Asia',
    'American Black Bear, Ursus americanus, North America',
    'Asian Black Bear, Ursus thibetanus, East Asia',
    'Polar Bear, Ursus maritimus, Arctic Circle',
    'Brown Bear, Ursus arctos, Eurasia/North America'
  ],
  'hyena': [
    'Aardwolf, Proteles cristatus, South/East Africa',
    'Spotted Hyena, Crocuta crocuta, Sub-Saharan Africa',
    'Brown Hyena, Parahyaena brunnea, Southern Africa',
    'Striped Hyena, Hyaena hyaena, Africa/Middle East/India'
  ],
  'raccoon': [
    'Kinkajou, Potos flavus, Central/South America',
    'Crab Eating Raccoon, Procyon cancrivorus, Central/South America',
    'Common Raccoon, Procyon lotor, North America',
    'Cacomistle, Bassariscus sumichrasti, Mexico/Panama/Costa Rica',
    'Ringtail, Bassariscus astutus, North America',
    'Western Lowland Olingo, Bassaricyon medius, Panama/Colombia/Ecuador',
    'Eastern Lowland Olingo, Bassaricyon alleni, South America',
    'Northern Olingo, Bassaricyon gabbii, Central America',
    'Olinguito, Bassaricyon neblina, Colombia/Ecuador',
    'Ring-Tailed Coati, Nasua nasua, South America',
    'White-Nosed Coati, Nasua narica, Central America/Mexico',
    'Western Mountain Coati, Nasuella olivacea, Colombia/Ecuador',
    'Eastern Mountain Coati, Nasuella meridensis, Venezuela',
  ],
  'mongoose': [
    'Egyptian Mongoose, H. ichneumon, Mediterranean',
    'Indian Grey Mongoose, H. edwardsii, India/West Asia',
    'Javan Mongoose, H. javanicus, Asia',
    'Stripe-Necked Mongoose, H. vitticollis, India/Sri Lanka',
    'Crab-Eating Mongoose, H. urva, ',
    'Ruddy Mongoose, H. smithii, ',
    'Short-Tailed Mongoose, H. brachyurus, ',
    'Indian Brown Mongoose, H. fuscus, ',
    'Collared Mongoose, H. semitorquatus, ',
    'Long-Nosed Mongoose, H. naso, ',
  ]
}

export default animals;